server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: entities
  mapper-locations: classpath:mybatis/mapper/**/DeptMapper.xml

spring:
  application:
    name: springcloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                           #数据库连接池的最小维持连接数
      initial-size: 5                       #初始化连接数
      max-total: 5                          #最大连接数
      max-wait-millis: 200                  #等待连接获取的最大超时时间

eureka:
  client:
    service-url:
      defaultZone: http://eureka8003.com:8003/eureka/,http://eureka8004.com:8004/eureka/,http://eureka8005.com:8005/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}+"-hystrix"      #显示名称
    prefer-ip-address: true             #显示ip

#info配置
info:
  app.name:  springcloud1
  company.name: www.baidu.com1